export interface ArticleContent {
  introduction: string;
  sections: {
    title: string;
    content: string;
    subsections?: {
      title: string;
      content: string;
    }[];
  }[];
  conclusion: string;
  keyTakeaways: string[];
}

export interface Article {
  id: string;
  title: string;
 excerpt: string;
  category: string;
  readTime: string;
  publishedAt: string;
  tags: string[];
  featured: boolean;
  color?: string;
  content?: ArticleContent;
}

export const CATEGORY_IMAGES: Record<string, string> = {
  'Breaking News': 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800',
  'AI & Tech': 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
  'AI Tools': 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800',
  'Investice': 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800',
  'Vzdělávání': 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800',
  'CNC & Engineering': 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800',
  'Design': 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
  'Móda': 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800',
  'Modeling': 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
  'Zdraví': 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=800',
  'Hardware': 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
  'Robotika': 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
  'Zahrada': 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
  'Zahrádka': 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
  'Zvířata': 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800',
  'Auta': 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
  'AI': 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
  'Novinky': 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800',
  'Náboženství': 'https://images.unsplash.com/photo-1509191442429-c495fb2c3f54?w=800',
};

export const GARDEN_ARTICLES = [
  {
    id: "zahrada-jaro-leto-pestovani",
    title: "🌱 Kompletní průvodce péčí o zahradu na jaro a léto",
    excerpt: "Vše co potřebujete vědět o jarní přípravě zahrady, výsevu, hnojení a letní údržbě. Od základů po pokročilé techniky pro bohatou úrodu.",
    category: "Zahrada",
    readTime: "15 min",
    publishedAt: "2026-03-15",
    tags: ["Zahrada", "Pěstování", "Jaro", "Léto", "Údržba", "Zelenina"],
    featured: true,
    color: "success",
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    icon: '🌱',
  },
  {
    id: "udrzba-stromu-a-kefu",
    title: "🌳 Řez stromů a keřů: Kdy, jak a proč? Kompletní průvodce",
    excerpt: "Naučte se správný řez ovocných stromů, okrasných keřů a živých plotů. Zásady bezpečnosti, správné nářadí a termíny pro jednotlivé dřeviny.",
    category: "Zahrada",
    readTime: "18 min",
    publishedAt: "2026-03-10",
    tags: ["Stromy", "Keře", "Řez", "Údržba", "Zahrada", "Nářadí"],
    featured: true,
    color: "success",
    image: 'https://images.unsplash.com/photo-1542361345-89e58247f2d5?w=800',
    icon: '🌳',
  },
  {
    id: "sazeni-sazenice-postup",
    title: "🌿 Jak správně sázet sazenice: Krok za krokem od semínka k úrodě",
    excerpt: "Detailní návod jak předpěstovat sazenice, kdy je vysadit na záhon a jak o ně pečovat. Tipy pro rajčata, papriky, okurky a další plodiny.",
    category: "Zahrada",
    readTime: "12 min",
    publishedAt: "2026-03-05",
    tags: ["Sázení", "Sazenice", "Semínka", "Pěstování", "Zelenina", "Jaro"],
    featured: true,
    color: "success",
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800',
    icon: '🌿',
  },
  {
    id: "grilovani-priprava-sezona",
    title: "🔥 Grilovací sezóna 2026: Příprava grilu, marinády a tipy pro dokonalé maso",
    excerpt: "Jak připravit gril po zimě, nejlepší marinády, teploty a časy pro různé druhy masa. Základy přímého a nepřímého grilování.",
    category: "Zahrada",
    readTime: "14 min",
    publishedAt: "2026-04-01",
    tags: ["Grilování", "Gril", "Maso", "Marinády", "Léto", "Vaření"],
    featured: true,
    color: "warning",
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    icon: '🔥',
  },
  {
    id: "bazen-priprava-udrzba",
    title: "🏊 Příprava bazénu na sezónu: Od zazimování po křišťálově čistou vodu",
    excerpt: "Kompletní návod jak zprovoznit bazén po zimě, nastavení chemie, údržba filtrace a tipy pro ekonomický provoz. Jak ušetřit na energiích.",
    category: "Zahrada",
    readTime: "16 min",
    publishedAt: "2026-04-10",
    tags: ["Bazén", "Údržba", "Chemie", "Voda", "Léto", "Zahrada"],
    featured: true,
    color: "info",
    image: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800',
    icon: '🏊',
  },
  {
    id: "sekani-travy-koseni",
    title: "🌾 Dokonalý trávník: Sekání, hnojení a boj s plevely",
    excerpt: "Jak často sekávat trávu, na jakou výšku, jak bojovat s mechem a plevely. Sezónní údržba trávníku od jara do podzimu pro zelený koberec.",
    category: "Zahrada",
    readTime: "13 min",
    publishedAt: "2026-03-20",
    tags: ["Trávník", "Sekání", "Kosení", "Údržba", "Zahrada", "Hnojení"],
    featured: true,
    color: "success",
    image: 'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
    icon: '🌾',
  },

  // Zvířata na zahrádce
  {
    id: "chovani-slepic-zakladni-pruvodce",
    title: "🐔 Chování slepic: Proč zobou, kdákají a klovají? Kompletní průvodce",
    excerpt: "Slepice mají složitější sociální strukturu, než si myslíte. Pochopte hierarchii hejna, komunikaci kdákáním a důvody agresivního chování. Tipy jak zajistit klidné hejno.",
    category: "Zvířata",
    readTime: "14 min",
    publishedAt: "2026-02-05",
    tags: ["Slepice", "Chov", "Chování", "Zahrádka", "Drůbež", "Hejno"],
    featured: true,
    color: "warning",
    image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800',
    icon: '🐔',
  },
  {
    id: "slepice-jak-zacit-chov",
    title: "🥚 Jak začít chovat slepice na zahrádce: Od kurníku po první vejce",
    excerpt: "Kompletní návod pro začínající chovatele slepic. Výběr plemene, stavba kurníku, krmení, zdravotní péče a co čekat v prvních měsících. Kolik slepic potřebujete na rodinu?",
    category: "Zvířata",
    readTime: "18 min",
    publishedAt: "2026-02-01",
    tags: ["Slepice", "Kurník", "Vejce", "Chov", "Začátečník", "Plemeno"],
    featured: true,
    color: "warning",
    image: 'https://images.unsplash.com/photo-1569428034239-f9565e32e224?w=800',
    icon: '🥚',
  },
  {
    id: "slepice-nemoci-prevence",
    title: "💊 Nemoci slepic: Jak poznat nemocnou slepici a co dělat",
    excerpt: "Naučte se rozpoznat příznaky nejčastějších nemocí drůbeže - od kokcidiózy po slepičí rýmu. Prevence, léčba a kdy volat veterináře. Domácí léčba přírodními prostředky.",
    category: "Zvířata",
    readTime: "16 min",
    publishedAt: "2026-01-28",
    tags: ["Slepice", "Nemoci", "Prevence", "Veterinář", "Zdraví", "Drůbež"],
    featured: true,
    color: "danger",
    image: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=800',
    icon: '💊',
  },
  {
    id: "kralici-na-zahrade-chov",
    title: "🐰 Králíci na zahradě: Chov, krmení a přátelské soužití s přírodou",
    excerpt: "Králíci jsou ideální zvířata na zahrádku - tichí, nenáročí a hnojí záhony. Jak postavit králíkárnu, co krmit, jak rozpoznat pohlaví a zvládnout rozmnožování.",
    category: "Zvířata",
    readTime: "15 min",
    publishedAt: "2026-01-25",
    tags: ["Králíci", "Chov", "Zahrádka", "Krmení", "Králíkárna"],
    featured: true,
    color: "info",
    image: 'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800',
    icon: '🐰',
  },
  {
    id: "vcely-na-zahrade-zakladni-pruvodce",
    title: "🐝 Včelaření pro začátečníky: Jak mít vlastní med ze zahrady",
    excerpt: "Včely pomáhají opylovat zahradu a dávají med. Základy včelaření, co potřebujete na start, jak manipulovat s úlem a kdy stáčet med. Včelí rok měsíc po měsíci.",
    category: "Zvířata",
    readTime: "20 min",
    publishedAt: "2026-01-20",
    tags: ["Včely", "Včelaření", "Med", "Opylení", "Úl", "Zahrádka"],
    featured: true,
    color: "warning",
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800',
    icon: '🐝',
  },
  {
    id: "kachny-husy-na-zahrade",
    title: "🦆 Kachny a husy na zahradě: Hlídači, pleveložrouti a vejce zdarma",
    excerpt: "Kachny likvidují slimáky a husy fungují jako alarm. Jak je chovat, krmit a zajistit jim přístup k vodě. Srovnání plemen a tipy na společný chov se slepicemi.",
    category: "Zvířata",
    readTime: "13 min",
    publishedAt: "2026-01-18",
    tags: ["Kachny", "Husy", "Chov", "Zahrádka", "Drůbež", "Vejce"],
    featured: true,
    color: "info",
    image: 'https://images.unsplash.com/photo-1459682687441-7761439a709d?w=800',
    icon: '🦆',
  },
  {
    id: "kozy-na-zahrade-maso-mleko",
    title: "🐐 Kozy na zahrádce: Mléko, sýr a skvělá společnost",
    excerpt: "Kozy jsou chytré, přátelské a dají vám čerstvé mléko denně. Výběr plemene, ustájení, krmení, dojení a výroba domácího kozího sýra. Kozy jako přírodní sekačky.",
    category: "Zvířata",
    readTime: "17 min",
    publishedAt: "2026-01-15",
    tags: ["Kozy", "Mléko", "Sýr", "Chov", "Zahrádka", "Plemeno"],
    featured: true,
    color: "success",
    image: 'https://images.unsplash.com/photo-1524024973431-2ad916746264?w=800',
    icon: '🐐',
  },
];

export const ARTICLES: Article[] = [
  // Breaking News
  {
    id: "nvidia-groq-acquisition",
    title: "💥 NVIDIA kupuje Groq za miliardy: Největší akvizice AI čipů",
    excerpt: "NVIDIA oznámila akvizici startupu Groq zabývajícího se AI akcelerátory. Hodnota transakce přesahuje 20 miliard dolarů.",
    category: "Breaking News",
    readTime: "6 min",
    publishedAt: "2026-01-06",
    tags: ["NVIDIA", "Groq", "AI čipy", "Akvizice", "Hardware"],
    featured: true,
  },
  {
    id: "waymo-gemini-ai-assistant",
    title: "🚕 Waymo testuje Google Gemini jako AI asistenta v robotaxících",
    excerpt: "Waymo testuje Google Gemini jako AI asistenta ve svých samořízených taxících.",
    category: "Breaking News",
    readTime: "5 min",
    publishedAt: "2026-01-06",
    tags: ["Waymo", "Google Gemini", "Robotaxi", "AI asistent", "Autonomní vozidla"],
    featured: true,
  },
  {
    id: "minimax-m2-1-model",
    title: "💻 MiniMax představuje M2.1: Nový model překonává konkurenci",
    excerpt: "MiniMax oznámil uvedení nového modelu M2.1 s vylepšeným multi-language programováním.",
    category: "Breaking News",
    readTime: "5 min",
    publishedAt: "2026-01-06",
    tags: ["MiniMax", "AI model", "Programování", "M2.1", "Benchmarky"],
    featured: true,
  },
  
  // AI & Tech
  {
    id: "windsurf-wave-13-multi-agent",
    title: "🚀 Windsurf Wave 13: Revoluce v multi-agent programování",
    excerpt: "Windsurf přináší Wave 13 s podporou paralelních multi-agent sessions.",
    category: "AI & Tech",
    readTime: "8 min",
    publishedAt: "2026-01-06",
    tags: ["Windsurf", "Wave 13", "Multi-agent", "Cascade", "IDE"],
    featured: true,
  },
  {
    id: "windsurf-git-worktrees",
    title: "🌳 Git Worktrees ve Windsurf: Multiple sessions bez konfliktů",
    excerpt: "Windsurf nyní podporuje Git worktrees pro více sessions.",
    category: "AI & Tech",
    readTime: "6 min",
    publishedAt: "2026-01-06",
    tags: ["Windsurf", "Git", "Worktrees", "Multi-agent", "Cascade"],
    featured: true,
  },
  {
    id: "meta-alexandr-wang-micromanagement",
    title: "😤 Meta's top AI hire Alexandr Wang se pod Zuckerbergovým mikromanagementem dusí",
    excerpt: "Alexandr Wang není spokojený s přehnaným dohledem CEO Marka Zuckerberga.",
    category: "AI & Tech",
    readTime: "7 min",
    publishedAt: "2026-01-06",
    tags: ["Meta", "Alexandr Wang", "Scale AI", "Zuckerberg", "Micromanagement", "AI"],
    featured: true,
  },
  {
    id: "nvidia-rubin",
    title: "🚀 NVIDIA představuje revoluční Rubin architekturu pro AI superpočítače",
    excerpt: "NVIDIA odhalila Rubin, zcela novou rack-scale AI platformu.",
    category: "AI & Tech",
    readTime: "10 min",
    publishedAt: "2026-01-06",
    tags: ["NVIDIA", "Rubin", "AI", "Čipy", "Superpočítač"],
    featured: true,
  },
  {
    id: "nvidia-alpamayo",
    title: "🚗 NVIDIA spouští Alpamayo: Open-source modely pro autonomní vozidla",
    excerpt: "NVIDIA představila Alpamayo, sadu open-source AI modelů.",
    category: "AI & Tech",
    readTime: "8 min",
    publishedAt: "2026-01-06",
    tags: ["NVIDIA", "Alpamayo", "Autonomní vozidla", "AI", "Open-source"],
    featured: true,
  },
  {
    id: "clickup-super-agents-introduction",
    title: "🤖 Introducing: Super Agents™ - AI Týmoví Spolupracovníci",
    excerpt: "ClickUp představuje Super Agents - první AI kolegy s nadlidskými schopnostmi.",
    category: "AI & Tech",
    readTime: "10 min",
    publishedAt: "2026-01-08",
    tags: ["ClickUp", "Super Agents", "AI", "Productivity", "Automation", "MCP"],
    featured: true,
  },

  // AI Tools
  {
    id: "leania-ai-audit",
    title: "⚙️ Leania.ai: Audit vašeho workflow a technologického stacku",
    excerpt: "Leania.ai analyzuje vaše pracovní postupy a technologický stack.",
    category: "AI Tools",
    readTime: "6 min",
    publishedAt: "2026-01-06",
    tags: ["Leania", "Audit", "Workflow", "Automatizace"],
    featured: true,
  },

  // Investice
  {
    id: "investice-2026-prehled",
    title: "📈 Investice v roce 2026: Přehled globálních trhů a příležitostí",
    excerpt: "Komplexní přehled investičních příležitostí v roce 2026.",
    category: "Investice",
    readTime: "12 min",
    publishedAt: "2026-01-06",
    tags: ["Investice", "Akcie", "Krypto", "Komodity", "2026"],
    featured: true,
  },
  {
    id: "bitcoin-rally-2026",
    title: "₿ Bitcoin se vrací: Cena překonává 93 700 $ a analytici jsou bullish",
    excerpt: "Bitcoin překonal hranici 93 700 $, analytici jsou optimističtí.",
    category: "Investice",
    readTime: "8 min",
    publishedAt: "2026-01-06",
    tags: ["Bitcoin", "Kryptoměny", "Investice", "Cena BTC"],
    featured: true,
  },
  {
    id: "amd-nvidia-ai-zavod",
    title: "🎯 AMD vs NVIDIA: Závod o dominanci v AI čipech se vyostřuje",
    excerpt: "AMD představila čip MI455 s 70 % více tranzistory.",
    category: "Investice",
    readTime: "10 min",
    publishedAt: "2026-01-06",
    tags: ["AMD", "NVIDIA", "AI čipy", "Investice", "Technologie"],
    featured: true,
  },

  // Robotika
  {
    id: "humanoidni-roboty-2026",
    title: "Humanoidní Roboti 2026: Nová éra robotiky",
    excerpt: "Přehled nejnovějších humanoidních robotů od Figure AI, Boston Dynamics, Tesla.",
    category: "Robotika",
    readTime: "20 min",
    publishedAt: "2025-01-06",
    tags: ["Humanoidní roboti", "Figure AI", "Boston Dynamics", "Tesla Optimus", "Robotika", "AI"],
    featured: true,
  },

  // AI
  {
    id: "mcp-model-context-protocol",
    title: "MCP - Model Context Protocol: Revoluce v AI",
    excerpt: "Anthropic představuje MCP protokol pro propojení AI modelů s datovými zdroji.",
    category: "AI",
    readTime: "18 min",
    publishedAt: "2025-01-06",
    tags: ["MCP", "Model Context Protocol", "Anthropic", "AI", "API", "Integrace"],
    featured: true,
  },

  // Zdraví
  {
    id: "kalendarni-vek-vs-biologicky-vek",
    title: "📅 Kalendářní věk měj v piči, důležitej je biologickej věk",
    excerpt: "Proč je číslo v občance jen statistika a skutečný věk se skrývá hlouběji.",
    category: "Zdraví",
    readTime: "10 min",
    publishedAt: "2026-01-08",
    tags: ["Zdraví", "Biologický věk", "Stárnutí", "Wellness", "Delší život"],
    featured: true,
  },

  // Hardware
  {
    id: "nvidia-older-gpus",
    title: "🔄 NVIDIA zvažuje oživení starších GPU",
    excerpt: "NVIDIA by mohla obnovit výrobu starších grafických karet.",
    category: "Hardware",
    readTime: "5 min",
    publishedAt: "2026-01-08",
    tags: ["NVIDIA", "GPU", "Hardware", "Gaming", "AI"],
    featured: true,
  },

  // CNC & Engineering
  {
    id: "cnc-programming-web-developer",
    title: "🔧 CNC Programování pro Web Vývojáře - Úvod do G-kódu",
    excerpt: "Jak využít své programátorské dovednosti ve světě výroby.",
    category: "CNC & Engineering",
    readTime: "12 min",
    publishedAt: "2026-01-08",
    tags: ["CNC", "G-kód", "CAD", "CAM", "Programování", "Výroba"],
    featured: true,
  },
  {
    id: "cad-cam-software-srovnani-2026",
    title: "📊 Srovnání CAD/CAM Softwaru 2026 - Autodesk vs Alternativy",
    excerpt: "Kompletní srovnání Fusion 360, FreeCAD, Mastercam, SolidWorks.",
    category: "CNC & Engineering",
    readTime: "15 min",
    publishedAt: "2026-01-08",
    tags: ["CAD", "CAM", "Fusion 360", "FreeCAD", "Mastercam", "Software", "Výroba"],
    featured: true,
  },
  {
    id: "cnc-simulatory-kde-trenovat",
    title: "🖥️ CNC Simulátory - Kde Trénovat G-kód Bez Stroje",
    excerpt: "Přehled dostupných CNC simulátorů od zdarma po profesionální.",
    category: "CNC & Engineering",
    readTime: "10 min",
    publishedAt: "2026-01-08",
    tags: ["CNC", "Simulátor", "G-kód", "Trénink", "CAMotics", "Fagor"],
    featured: true,
  },

  // Auta
  {
    id: "tesla-model-2-2026",
    title: "⚡ Tesla Model 2 konečně odhalena: Elektromobil za 25 000 $ mění trh",
    excerpt: "Tesla představila dlouho očekávaný Model 2 s cenou pod 600 000 Kč. Dojezd 400 km, nabíjení 15 min na 80% a kompaktní design. Jak se porovnává s konkurencí?",
    category: "Auta",
    readTime: "8 min",
    publishedAt: "2026-02-08",
    tags: ["Tesla", "Model 2", "Elektromobil", "EV", "Cenově dostupný"],
    featured: true,
  },
  {
    id: "bmw-neue-klasse-2026",
    title: "🏎️ BMW Neue Klasse 2026: Nová éra bavorských elektromobilů",
    excerpt: "BMW spouští revoluci s platformou Neue Klasse. Nový iX3 nabídne 800V architekturu, dojezd 700 km a futuristický interiér s panoramatickým HUD. Ceny a dostupnost v ČR.",
    category: "Auta",
    readTime: "10 min",
    publishedAt: "2026-02-06",
    tags: ["BMW", "Neue Klasse", "iX3", "Elektromobil", "800V", "Premium"],
    featured: true,
  },
  {
    id: "xiaomi-su7-ultra-rekord",
    title: "🇨🇳 Xiaomi SU7 Ultra: Čínský elektromobil zlomil rekord Nürburgringu",
    excerpt: "Xiaomi SU7 Ultra s 1 548 koňmi překonal Porsche Taycan na Nürburgringu. Čas 6:46.874 z něj dělá nejrychlejší sériový elektromobil. Jak se z výrobce telefonů stal automobilka?",
    category: "Auta",
    readTime: "7 min",
    publishedAt: "2026-02-04",
    tags: ["Xiaomi", "SU7 Ultra", "Nürburgring", "Rekord", "Čína", "EV"],
    featured: true,
  },
  {
    id: "hyundai-ioniq-9-recenze",
    title: "🚙 Hyundai IONIQ 9: Rodinný elektro-kolos s dojezdem 620 km",
    excerpt: "Největší elektromobil od Hyundai nabídne 3 řady sedadel, 800V nabíjení a luxusní interiér s otočnými sedadly. Konkurence pro Tesla Model X za výrazně nižší cenu.",
    category: "Auta",
    readTime: "9 min",
    publishedAt: "2026-02-02",
    tags: ["Hyundai", "IONIQ 9", "SUV", "Elektromobil", "Rodina", "800V"],
    featured: true,
  },
  {
    id: "skoda-elroq-prvni-dojmy",
    title: "🇨🇿 Škoda Elroq: První české kompaktní elektro SUV v prodeji",
    excerpt: "Škoda Elroq konečně dorazila k českým dealerům. Dojezd až 560 km, MEB platforma, prostorný interiér a cena od 899 000 Kč. Test spotřeby v reálném provozu.",
    category: "Auta",
    readTime: "11 min",
    publishedAt: "2026-01-30",
    tags: ["Škoda", "Elroq", "Elektromobil", "SUV", "České", "MEB"],
    featured: true,
  },

  // AI objevy
  {
    id: "claude-opus-4-revoluce",
    title: "🧠 Claude Opus 4: Nejinteligentnější AI model na světě?",
    excerpt: "Anthropic vydal Claude Opus 4 s revolučními schopnostmi uvažování, kódování a analýzy. Benchmarky ukazují překonání GPT-5 i Gemini Ultra 2. Co to znamená pro budoucnost AI?",
    category: "AI",
    readTime: "12 min",
    publishedAt: "2026-02-10",
    tags: ["Claude", "Anthropic", "Opus 4", "LLM", "AGI", "Benchmarky"],
    featured: true,
  },
  {
    id: "openai-sora-2-video-generovani",
    title: "🎬 OpenAI Sora 2: Generování filmových videí v 4K za minuty",
    excerpt: "Nová verze Sora generuje až 5minutová videa v kinematografické kvalitě. Fyzikální simulace, konzistentní postavy a přímá integrace s editačním softwarem. Hollywood je nervózní.",
    category: "AI",
    readTime: "9 min",
    publishedAt: "2026-02-08",
    tags: ["OpenAI", "Sora 2", "Video AI", "Generování", "4K", "Film"],
    featured: true,
  },
  {
    id: "google-deepmind-alphafold-3-leky",
    title: "💊 AlphaFold 3 objevil 3 nové léky: AI revoluce ve farmacii",
    excerpt: "DeepMind oznámil, že AlphaFold 3 identifikoval molekuly pro léčbu Alzheimera, rezistentní TBC a vzácné genetické choroby. Klinické testy začínají v Q2 2026.",
    category: "AI",
    readTime: "10 min",
    publishedAt: "2026-02-05",
    tags: ["DeepMind", "AlphaFold 3", "Léky", "Farmacie", "Alzheimer", "Zdraví"],
    featured: true,
  },
  {
    id: "ai-roboti-humanoidni-2026",
    title: "🤖 Humanoidní roboti 2026: Figure 02, Tesla Optimus a čínský úder",
    excerpt: "Rok 2026 je rokem humanoidních robotů. Figure 02 pracuje ve skladech BMW, Tesla Optimus zvládá domácí úkoly a čínský Unitree G1 stojí jen 16 000 $. Přehled a srovnání.",
    category: "AI",
    readTime: "14 min",
    publishedAt: "2026-02-03",
    tags: ["Roboti", "Humanoid", "Figure", "Tesla Optimus", "Unitree", "Automatizace"],
    featured: true,
  },
  {
    id: "ai-agenti-autonomni-kodovani",
    title: "💻 AI agenti kódují celé aplikace: Devin, Claude Code a SWE-bench revoluce",
    excerpt: "Nová generace AI agentů dokáže samostatně vytvořit kompletní webovou aplikaci. Devin 2.0, Claude Code a Copilot Workspace řeší 70%+ reálných GitHub issues. Konec juniorních programátorů?",
    category: "AI",
    readTime: "11 min",
    publishedAt: "2026-01-28",
    tags: ["AI Agent", "Devin", "Claude Code", "Kódování", "SWE-bench", "Automatizace"],
    featured: true,
  },

  // Religion articles
  {
    id: "svetova-nabozenstvi-prehled",
    title: "🌍 Světová náboženství: Průvodce hlavními vírami lidstva",
    excerpt: "Křesťanství, islám, hinduismus, buddhismus a judaismus - pět největších náboženství světa. Jejich historie, učení, rituály a vliv na miliardy lidí.",
    category: "Náboženství",
    readTime: "18 min",
    publishedAt: "2026-04-15",
    tags: ["Náboženství", "Křesťanství", "Islám", "Hinduismus", "Buddhismus", "Judaismus", "Kultura"],
    featured: true,
  },
  {
    id: "historie-krestanstvi",
    title: "✝️ Křesťanství: Od Golgoty k miliardě věřících",
    excerpt: "Dva tisíce let historie nejrozšířenějšího náboženství. Od apoštolů přes středověké scholastiky až po současnou globalizovanou cirkev.",
    category: "Náboženství",
    readTime: "15 min",
    publishedAt: "2026-04-10",
    tags: ["Křesťanství", "Historie", "Bible", "Církev", "Vatikán"],
    featured: false,
  },
  {
    id: "islam-historie-a-kultura",
    title: "☪️ Islám: Víra, tradice a moderní svět",
    excerpt: "Původ islámu, prorok Muhammad, Korán a pět pilířů islámu. Jak islám formoval kulturu a civilizace po celém světě.",
    category: "Náboženství",
    readTime: "16 min",
    publishedAt: "2026-04-05",
    tags: ["Islám", "Korán", "Muhammad", "Arabská kultura", "Blízký východ"],
    featured: false,
  },
  {
    id: "buddhismus-cesta-k-osvobozeni",
    title: "🧘 Buddhismus: Cesta k osvobození od utrpení",
    excerpt: "Buddha, čtyři ušlechtilé pravdy, meditace a mindfulness. Jak buddhistická filozofie ovlivnila západní psychologii a populární kulturu.",
    category: "Náboženství",
    readTime: "14 min",
    publishedAt: "2026-03-28",
    tags: ["Buddhismus", "Meditace", "Buddha", "Mindfulness", "Filozofie"],
    featured: false,
  },
  {
    id: "bible-kniha-knih",
    title: "📖 Bible: Nejvlivnější kniha v dějinách lidstva",
    excerpt: "Starý a Nový zákon, bible jako literární dílo a náboženský text. Její vliv na literaturu, umění, filozofii a západní civilizaci.",
    category: "Náboženství",
    readTime: "12 min",
    publishedAt: "2026-03-20",
    tags: ["Bible", "Starý zákon", "Nový zákon", "Literatura", "Historie"],
    featured: false,
  },

  // Add garden articles to main list too
  ...GARDEN_ARTICLES,
];

export function getCategoryPriority(category: string): number {
  const priority: Record<string, number> = {
    'Breaking News': 1,
    'AI & Tech': 2,
    'AI Tools': 3,
    'AI': 4,
    'Auta': 5,
    'Investice': 6,
    'Zahrada': 7,
    'Zvířata': 8,
    'CNC & Engineering': 9,
    'Robotika': 10,
    'Design': 11,
    'Móda': 12,
    'Modeling': 13,
    'Zdraví': 14,
    'Hardware': 15,
    'Náboženství': 16,
  };
  return priority[category] || 99;
}
